### DISCUSSION TITLE
DNS interface keeps getting changed

### DISCUSSION THREAD

**Discussion by andcbii** [lovelaze/nebula-sync#150] [Q&A]
On the host I'm syncing to DNS Settings-> Interface settings keep changing. I've added SYNC_CONFIG_DNS_EXCLUDE=interface to my yaml, but it's still happing. What am i doing wrong. Here is my compose file

``` yml
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - CLIENT_SKIP_TLS_VERIFICATION=true
    - PRIMARY=http://192.168.10.31:81|PW
    - REPLICAS=http://192.168.10.14|PW
    - FULL_SYNC=false
    - SYNC_CONFIG_DNS=true #Synchronize DNS settings
    - SYNC_CONFIG_DNS_EXCLUDE=interface
    - SYNC_CONFIG_DHCP=false #Synchronize DHCP settings
    - SYNC_CONFIG_NTP=false #Synchronize NTP settings
    - SYNC_CONFIG_RESOLVER=true #Synchronize resolver settings
    - SYNC_CONFIG_DATABASE=false #Synchronize database settings
    - SYNC_CONFIG_MISC=false #Synchronize miscellaneous settings
    - SYNC_CONFIG_DEBUG=false #Synchronize debug settings
    - SYNC_GRAVITY_DHCP_LEASES=false #Synchronize DHCP leases
    - SYNC_GRAVITY_GROUP=true #Synchronize groups
    - SYNC_GRAVITY_AD_LIST=true #Synchronize ad lists
    - SYNC_GRAVITY_AD_LIST_BY_GROUP=true #Synchronize ad lists by group
    - SYNC_GRAVITY_DOMAIN_LIST=true #Synchronize domain lists
    - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true #Synchronize domain lists by group
    - SYNC_GRAVITY_CLIENT=true #Synchronize clients
    - SYNC_GRAVITY_CLIENT_BY_GROUP=true #Synchronize clients by group
    - RUN_GRAVITY=true
    - CRON=0 * * * *
```
