### ISSUE TITLE
How to configure paswordless pihole?

### ISSUE THREAD

**Issue by cierzniak** [lovelaze/nebula-sync#10]
I setup my pihole without passwords and nebula displays:

```
INF Running full sync replicas=1
INF Authenticating clients...
ERR Sync failed error="authenticate: no sid found"
```

How to configure that? Now my compose.yaml contains pihole & nebula service configured like that

```
services:
  app:
    restart: unless-stopped
    hostname: dns-server2
    image: pihole/pihole:development
    environment:
      TZ: Europe/Warsaw
      FTLCONF_webserver_api_password: ''
    volumes:
    - app_config:/etc/pihole:rw
    - app_dnsmasq:/etc/dnsmasq.d:rw
    ports:
    - '0.0.0.0:53:53/tcp'
    - '0.0.0.0:53:53/udp'
    - '0.0.0.0:8001:80/tcp'
    cap_add:
    - NET_ADMIN
  sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    environment:
      PRIMARY: 'http://10.0.0.117|'
      REPLICAS: 'http://app|'
      FULL_SYNC: 'true'
      CRON: '*/5 * * * *'

volumes:
  app_config: ~
  app_dnsmasq: ~
```
