### ISSUE TITLE
Issue with multiple DHCP enabled instances

### ISSUE THREAD

**Issue by mightyBroccoli** [lovelaze/nebula-sync#123]
I am running the following configuration. I have a "main" pihole configured with a dhcp section a and a backup pihole also dhcp enabled running with a separate dhcp range b, configured to be slower with the included 'dnsmasq_lines' below.

Would it be an option that nebular retrieves all lease files from main and all replicas that have dhcp enabled and merges them before pushing the merged list to all instances. This would ensure that single DHCP and multi DHCP setups have the correct lease list on all devices.

```yaml
---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://pihole.example.local|password
    - REPLICAS=http://pihole2.example.local|password
    - CLIENT_SKIP_TLS_VERIFICATION=true
    - TZ=Europe/Berlin
    - CRON=0 * * * *

    # SYNC SETTINGS
    - FULL_SYNC=false
    - RUN_GRAVITY=true

    - SYNC_CONFIG_DNS=true
    - SYNC_CONFIG_DHCP=true
    - SYNC_CONFIG_NTP=true
    - SYNC_CONFIG_RESOLVER=true
    - SYNC_CONFIG_DATABASE=true
    - SYNC_CONFIG_MISC=true
    - SYNC_CONFIG_DEBUG=false

   # enabled lease list merge with for example SYNC_GRAVITY_DHCP_LEASES=merge
    - SYNC_GRAVITY_DHCP_LEASES=false

    - SYNC_GRAVITY_GROUP=true
    - SYNC_GRAVITY_AD_LIST=true
    - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
    - SYNC_GRAVITY_DOMAIN_LIST=true
    - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
    - SYNC_GRAVITY_CLIENT=true
    - SYNC_GRAVITY_CLIENT_BY_GROUP=true

    # DHCP EXCLUDES
    - SYNC_CONFIG_DHCP_EXCLUDE=active,start,end

    # MISC EXCLUDES
    - SYNC_CONFIG_MISC_EXCLUDE=dnsmasq_lines
```

```conf
# define secondary dns server
dhcp-option=6,10.11.12.2,10.11.12.3
# increase dhcp response delay
dhcp-reply-delay=5
```
