### ISSUE TITLE
8080 is in use

### ISSUE THREAD

**Issue by DuzAwe** [lovelaze/nebula-sync#135]
Hi,

I see you have defaulted health checks to 8080. 8080 is an incredibly common port that is in use already in a lot of projects. How can I change the port for nebula?

**Comment by lovelaze** [comment]
Hi @DuzAwe 

Could you explain your scenario how it conflicts? The port is not exposed in the docker file

There is no way to change the port right now, currently it's just an internal endpoint

**Comment by lovelaze** [comment]
Please share your docker configuration

**Comment by DuzAwe** [comment]
Im using the 8080 elsewhere in my system its not in my compose file.

**Comment by DuzAwe** [comment]
```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      br0:
        ipv4_address: 192.168.0.52
    #network_mode: host
    #ipv4_address: 192.168.0.52
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 192.168.0.52:53:53/tcp
      - 192.168.0.52:67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - 192.168.0.52:53:53/udp
      - 192.168.0.52:80:80/tcp
    environment:
      TZ: 'GMT'
      PIHOLE_DNS_: '9.9.9.9;149.112.112.112'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/user/appdata/pihole/pihole/:/etc/pihole'
      - '/mnt/user/appdata/pihole/dnsmasq.d/:/etc/dnsmasq.d'
    #https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always

  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:v0.10.0
    container_name: nebula-sync
    network_mode: host
    environment:
    - PRIMARY=http://192.168.0.52|dasdsadasd
    - REPLICAS=http://192.168.0.128|adasdasdads
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    - API_ENABLED=false / NEW Not there when ticket opened
    
networks:
  br0:
    external: true
```
