### ISSUE TITLE
Unexpected status code: 404

### ISSUE THREAD

**Issue by VivaPitagoras** [lovelaze/nebula-sync#136]
I am using Pi-hole v6.0.6 installed via docker and I am getting the following error:

```
docker logs -f nebula-sync
2025-04-25T17:36:03Z INF Starting nebula-sync v0.11.0
2025-04-25T17:36:03Z INF Running sync mode=full replicas=1
2025-04-25T17:36:03Z INF Authenticating clients...
2025-04-25T17:36:03Z INF Invalidating sessions...
2025-04-25T17:36:03Z WRN Failed to invalidate session for target: http://192.168.1.165
2025-04-25T17:36:05Z FTL Sync failed error="authenticate: http://192.168.1.165/api/auth: unexpected status code: 404"
2025-04-25T17:36:05Z WRN Failed to invalidate session for target: http://192.168.1.160
```

This is my compose:
```

---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://192.168.1.165|pass
    - REPLICAS=http://192.168.1.160|pass
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
```

If I try to get /api/auth I get;

```
 curl -v http://192.168.1.165/api/auth
*   Trying 192.168.1.165:80...
* Connected to 192.168.1.165 (192.168.1.165) port 80
> GET /api/auth HTTP/1.1
> Host: 192.168.1.165
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: openresty
< Date: Fri, 25 Apr 2025 18:08:26 GMT
< Content-Type: text/html
< Content-Length: 150
< Connection: keep-alive
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
* Connection #0 to host 192.168.1.165 left intact
```

**Comment by lovelaze** [comment]
Hi @VivaPitagoras 

This means that `http://192.168.1.165/api/auth` is not the url to your pihole v6 api.

> ```
> <center><h1>404 Not Found</h1></center>
> <hr><center>openresty</center>
> ```

Are you running a reverse proxy that fails to lookup the pihole? afaik openresty is not used in pihole

**Comment by VivaPitagoras** [comment]
Hi @lovelaze,

Thanks for the quick response. 

Yes, I am using NGINX Proxy Manager, but shouldn't the use of IP (and not subdomain.domain.tld) bypass it? You'll have to excuse my lack of knowledge in the matter but I've only being playing with proxies for a couple of weeks and I still have a lot to learn.

**Comment by VivaPitagoras** [comment]
I've finally managed to get it to work. The problem was that I was not specifying pi-hole port. Now its working:

```
---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://192.168.1.165**:8081**|pass
    - REPLICAS=http://192.168.1.160**:8081**|pass
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
```
