### ISSUE TITLE
Error 405

### ISSUE THREAD

**Issue by RikudouGoku** [lovelaze/nebula-sync#151]
I am running Pihole (with unbound) on both my Synology DS423+ and my Orange Pi 5 Plus, they both work but I cannot get Nebula-sync to work.  Synology is using docker while I installed it natively on the Pi. Here is the compose for pihole on the synology:

```
services:
  pihole-unbound:
    container_name: pihole-unbound
    image: mpgirro/pihole-unbound:latest
    hostname: pihole
    domainname: local
    ports:
      - "8444:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp" # Change if port 80 is already in use by Synology
      # - "5335:5335/tcp" # Uncomment if you want to expose Unbound directly
    environment:
      - TZ=Europe/Stockholm
      - FTLCONF_webserver_api_password=your_secure_password
      - FTLCONF_webserver_interface_theme=default-dark
      - FTLCONF_dns_revServers=false,,,
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_listeningMode=single
    volumes:
      - /volume2/docker2/pihole/etc-pihole:/etc/pihole:rw
      - /volume2/docker2/pihole/etc-dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped

```

I get this error log in nebula-sync:

```
2025-05-24T21:34:34+02:00` INF Starting nebula-sync v0.11.0

2025-05-24T21:34:34+02:00 INF Running sync mode=full replicas=1

2025-05-24T21:34:34+02:00 INF Authenticating clients...

2025-05-24T21:34:34+02:00 INF Invalidating sessions...

2025-05-24T21:34:34+02:00 WRN Failed to invalidate session for target: http://192.168.0.100

2025-05-24T21:34:36+02:00 WRN Failed to invalidate session for target: https://192.168.0.200

2025-05-24T21:34:36+02:00 FTL Sync failed error="authenticate: http://192.168.0.100/api/auth: unexpected status code: 405

```

Compose for nebula sync:
```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
      - PRIMARY=http://192.168.0.100|your_secure_password  
      - REPLICAS=https://192.168.0.200|Dn8_U0iC            
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=0 * * * *
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - TZ=Europe/Stockholm
```

After discussing it with chatbots, I suspect it has something to do with how my synology is redirecting "192.168.0.100" to "https://192.168.0.100:7777/" (in the browser at least) and "192.168.0.200" shows this:

![Image](https://github.com/user-attachments/assets/3caf2667-42f7-437f-b8a1-d93fce3cbd8e)

**Comment by RikudouGoku** [comment]
> Hi [@RikudouGoku](https://github.com/RikudouGoku)
> 
> This is an issue with your environment setup, it has nothing to do with nebula-sync.
> 
> https://192.168.0.200 doesn't point towards a pihole v6 API, but something else (synology most likely).
> 
> Looking at your pihole setup the exposed port for your pihole probably you can use either `https://192.168.0.200:8444` or `http://192.168.0.200:8081` instead (wild guess)

Thank you for the help!

This fixed it:


```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
      - PRIMARY=http://192.168.0.100:8081|your_secure_password  
      - REPLICAS=https://192.168.0.200:8443|Dn8_U0iC            
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=0 * * * *
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - TZ=Europe/Stockholm
```
