### ISSUE TITLE
Sync Failed - 400 error

### ISSUE THREAD

**Issue by youenl-dev** [lovelaze/nebula-sync#160]
Hi,

I'm trying to sync my 2 piholes both running in docker, WEBSERVER.API.APP_SUDO is also enabled on both devices. In the logs, it looks like everything works fine up until the invalidating sessions message:

```
nebula-sync  | 2025-06-14T15:47:47+01:00 INF Starting nebula-sync v0.11.0
nebula-sync  | 2025-06-14T15:47:47+01:00 INF Running sync mode=selective replicas=1
nebula-sync  | 2025-06-14T15:47:47+01:00 INF Authenticating clients...
nebula-sync  | 2025-06-14T15:47:48+01:00 INF Syncing teleporters...
nebula-sync  | 2025-06-14T15:47:48+01:00 INF Syncing configs...
nebula-sync  | 2025-06-14T15:47:52+01:00 INF Invalidating sessions...
nebula-sync  | 2025-06-14T15:47:52+01:00 FTL Sync failed error="sync configs: https://192.168.10.15/api/config: unexpected status code: 400"
nebula-sync exited with code 1
```

I've tried with both my admin password or app password, and the outcome is the same. Please find also below my docker-compose.yml:

```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - TZ=Europe/London
    - PRIMARY=https://192.168.10.14|appPassword01
    - REPLICAS=https://192.168.10.15|appPassword02
    - FULL_SYNC=false
    - RUN_GRAVITY=true
    - CLIENT_SKIP_TLS_VERIFICATION=true
    # Running every 60 minutes
    - CRON=*/60 * * * *
    # Enabling selective sync
    - SYNC_CONFIG_DNS=true
    - SYNC_CONFIG_DHCP=false
    - SYNC_CONFIG_NTP=false
    - SYNC_CONFIG_RESOLVER=false
    - SYNC_CONFIG_DATABASE=false
    - SYNC_CONFIG_MISC=false
    - SYNC_CONFIG_DEBUG=false
    - SYNC_GRAVITY_DHCP_LEASES=false
    - SYNC_GRAVITY_GROUP=false
    - SYNC_GRAVITY_AD_LIST=true
    - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
    - SYNC_GRAVITY_DOMAIN_LIST=true
    - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
    - SYNC_GRAVITY_CLIENT=false
    - SYNC_GRAVITY_CLIENT_BY_GROUP=false
```

DOCKER TAG [2025.06.2]
CORE [V6.1.2]
FTL [V6.2.3]
WEB INTERFACE [V6.2.1]

If anyone is able to help, that'd be much appreciated. Thank you!
