### ISSUE TITLE
Sync fails with error 400

### ISSUE THREAD

**Issue by diamkil** [lovelaze/nebula-sync#163]
Hello,

Trying to setup sync again as I previously used Orbital Sync on 5.x.

Here is the docker compose for nebula-sync:
```
  nebula-sync:
    container_name: nebula-sync
    image: ghcr.io/lovelaze/nebula-sync:latest
    restart: unless-stopped
    environment:
      - PRIMARY=http://pihole1.localdomain:8080|password
      - REPLICAS=http://pihole2.localdomain:8080|password
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=*/15 * * * *
      - TZ=America/Toronto
      - CLIENT_TIMEOUT_SECONDS=60
      - CLIENT_RETRY_DELAY_SECONDS=60
```

However, for some reason the sync seems to fail when launching the container:
```
2025-06-20T19:17:51-04:00 INF Starting nebula-sync v0.11.0
2025-06-20T19:17:51-04:00 INF Running sync mode=full replicas=1
2025-06-20T19:17:51-04:00 INF Authenticating clients...
2025-06-20T19:17:51-04:00 INF Syncing teleporters...
2025-06-20T19:17:52-04:00 INF Syncing configs...
2025-06-20T19:21:52-04:00 INF Invalidating sessions...
2025-06-20T19:21:52-04:00 FTL Sync failed error="sync configs: http://pihole2.localdomain:8080/api/config: unexpected status code: 400"
```

Could this be because of some locked parameters in Pi-Hole (set via environment)?
If so, does that mean I'll have to set Full Sync to false and manually include the parts not locked? Could the software auto detect those?

**Comment by lovelaze** [comment]
Hi @diamkil 

> Could this be because of some locked parameters in Pi-Hole (set via environment)? 

Most likely, you'll find the answer in the pihole logs of your replica.

> If so, does that mean I'll have to set Full Sync to false and manually include the parts not locked? 

Yes, you'll either have to do that or remove the read-only config keys in that pihole. 

> Could the software auto detect those?

Yes and no. This would not be difficult to implement, but it is currently not possible because the pihole API does not expose a way to fetch which config keys are read-only.

**Comment by diamkil** [comment]
Hello,
Looking at the pihole log I see nothing related to the sync, only query logs.
Do I need to change the log level or something to see the error in the log?

**Comment by saniac** [comment]
Am also seeing this exact error.

Running the binary directly, with this env file:

```
PRIMARY=https://pihole|[password]
REPLICAS=https://192.168.12.240|[password]
FULL_SYNC=true
RUN_GRAVITY=true
CLIENT_SKIP_TLS_VERIFICATION=true
```

I set "all = true" in the [debug] section of pihole.toml on the replica but don't see anything that relates.

**Comment by saniac** [comment]
I was able to stop this error from happening again. I did a manual export via Teleport from the primary, and a manual import via Teleport on the secondary. After that syncs succeeded.

**Comment by Meticulous7** [comment]
I found out this was due to trying to sync a regular Pihole install with a Docker install. The sync failed because my docker-compose.yml was setting ListeningMode to All, and Nebula cannot change config settings that are defined during the container deployment (they are greyed out in the GUI as well). I had to set 'FULLSYNC=false' and then add 'SYNC_CONFIG_DNS_EXCLUDE=listeningMode' to have it skip that value. After there, no more error 400

Only remaining issue is I can't get it to work with Gravity updates enabled. Otherwise, everything else is syncing great

Here is my current config if interested

```---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=https://pihole.myDomain.com|${PIHOLE_ADMIN_PASSWORD}
    - REPLICAS=https://pihole2.myDomain.com |${PIHOLE_ADMIN_PASSWORD}
    - FULL_SYNC=false
    - SYNC_CONFIG_DNS=true 	
    - SYNC_CONFIG_DNS_EXCLUDE=listeningMode
    - SYNC_CONFIG_DHCP=true 	
    - SYNC_CONFIG_NTP=true
    - SYNC_CONFIG_RESOLVER=true
    - SYNC_CONFIG_DATABASE=true
    - SYNC_CONFIG_MISC=true 
    - SYNC_CONFIG_DEBUG=false
    - SYNC_GRAVITY_DHCP_LEASES=true
    - SYNC_GRAVITY_GROUP=true
    - SYNC_GRAVITY_AD_LIST=true
    - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
    - SYNC_GRAVITY_DOMAIN_LIST=true
    - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
    - SYNC_GRAVITY_CLIENT=true
    - SYNC_GRAVITY_CLIENT_BY_GROUP=true
    - CLIENT_TIMEOUT_SECONDS=60
    - RUN_GRAVITY=false
    - TZ=America/New_York
    - CRON=*/5 * * * *```

**Comment by diamkil** [comment]
I will try what @Meticulous7 proposed, both my Pi-Holes are in Docker so this might be the solution

**Comment by m147** [comment]
> I found out this was due to trying to sync a regular Pihole install with a Docker install. The sync failed because my docker-compose.yml was setting ListeningMode to All, and Nebula cannot change config settings that are defined during the container deployment (they are greyed out in the GUI as well). I had to set "FULLSYNC=false" and then add SYNC_CONFIG_DNS_EXCLUDE=listeningMode" to have it skip that value. After there, no more error 400
> 
> Only remaining issue is I can't get it to work with Gravity updates enabled. Otherwise, everything else is syncing great
> 
> Here is my current config if interested
> 
> ```
> services:
>   nebula-sync:
>     image: ghcr.io/lovelaze/nebula-sync:latest
>     container_name: nebula-sync
>     environment:
>     - PRIMARY=https://pihole.meticulous.dev|${PIHOLE_ADMIN_PASSWORD}
>     - REPLICAS=https://pihole2.meticulous.dev|${PIHOLE_ADMIN_PASSWORD}
>     - FULL_SYNC=false
>     - SYNC_CONFIG_DNS=true 	
>     - SYNC_CONFIG_DNS_EXCLUDE=listeningMode
>     - SYNC_CONFIG_DHCP=true 	
>     - SYNC_CONFIG_NTP=true
>     - SYNC_CONFIG_RESOLVER=true
>     - SYNC_CONFIG_DATABASE=true
>     - SYNC_CONFIG_MISC=true 
>     - SYNC_CONFIG_DEBUG=false
>     - SYNC_GRAVITY_DHCP_LEASES=true
>     - SYNC_GRAVITY_GROUP=true
>     - SYNC_GRAVITY_AD_LIST=true
>     - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
>     - SYNC_GRAVITY_DOMAIN_LIST=true
>     - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
>     - SYNC_GRAVITY_CLIENT=true
>     - SYNC_GRAVITY_CLIENT_BY_GROUP=true
>     - CLIENT_TIMEOUT_SECONDS=60
>     - RUN_GRAVITY=false
>     - TZ=America/New_York
>     - CRON=*/5 * * * *```
> ```

FANTASTIC!!! Thank you so much for this!!!
I spent hours trying to set it up and nothing was working until I found your solution.

Any luck with figuring out the RUN_GRAVITY issue?

I suppose it's not a big deal if not, I can periodically update gravity manually.

**Comment by Meticulous7** [comment]
> 
> 
> 
> > I found out this was due to trying to sync a regular Pihole install with a Docker install. The sync failed because my docker-compose.yml was setting ListeningMode to All, and Nebula cannot change config settings that are defined during the container deployment (they are greyed out in the GUI as well). I had to set "FULLSYNC=false" and then add SYNC_CONFIG_DNS_EXCLUDE=listeningMode" to have it skip that value. After there, no more error 400
> > 
> > Only remaining issue is I can't get it to work with Gravity updates enabled. Otherwise, everything else is syncing great
> > 
> > Here is my current config if interested
> > 
> > ```
> > services:
> >   nebula-sync:
> >     image: ghcr.io/lovelaze/nebula-sync:latest
> >     container_name: nebula-sync
> >     environment:
> >     - PRIMARY=https://pihole.myDomain.com|${PIHOLE_ADMIN_PASSWORD}
> >     - REPLICAS=https://pihole2.myDomain.com|${PIHOLE_ADMIN_PASSWORD}
> >     - FULL_SYNC=false
> >     - SYNC_CONFIG_DNS=true 	
> >     - SYNC_CONFIG_DNS_EXCLUDE=listeningMode
> >     - SYNC_CONFIG_DHCP=true 	
> >     - SYNC_CONFIG_NTP=true
> >     - SYNC_CONFIG_RESOLVER=true
> >     - SYNC_CONFIG_DATABASE=true
> >     - SYNC_CONFIG_MISC=true 
> >     - SYNC_CONFIG_DEBUG=false
> >     - SYNC_GRAVITY_DHCP_LEASES=true
> >     - SYNC_GRAVITY_GROUP=true
> >     - SYNC_GRAVITY_AD_LIST=true
> >     - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
> >     - SYNC_GRAVITY_DOMAIN_LIST=true
> >     - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
> >     - SYNC_GRAVITY_CLIENT=true
> >     - SYNC_GRAVITY_CLIENT_BY_GROUP=true
> >     - CLIENT_TIMEOUT_SECONDS=60
> >     - RUN_GRAVITY=false
> >     - TZ=America/New_York
> >     - CRON=*/5 * * * *```
> > ```
> 
> FANTASTIC!!! Thank you so much for this!!!
> I spent hours trying to set it up and nothing was working until I found your solution.
> 
> Any luck with figuring out the RUN_GRAVITY issue?
> 
> I suppose it's not a big deal if not, I can periodically update gravity manually.

Glad to hear it!

Unfortunately I have not, but I will for sure update this thread if I do.

If I can't, my workaround plan will be to see if I can update Gravity via the Pi-hole API. If that succeeds, I will run it daily via a CICD pipeline on my local GitLab server

**Comment by cjlindem** [comment]
This helped me solve my error as well.  
`FTL Sync failed error="sync configs: http://192.168.0.102:180/api/config: unexpected status code: 400"`

I set up a 2nd Pihole last night and sync'd it successfully with nebula-sync.  Somewhere thereafter I noticed a setting in my compose.yml file - "FTLCONF_dns_listeningMode: " with a comment indicating this was good to enable if PiHole was operating in bridge mode.  I am in bridge mode, so I enabled it.  However, it was not enabled on the primary PiHole instance.  Later, my syncs started failing.  I've toggled this setting on and off in my 2nd Pihole's stack and confirmed that when it matches the Primary Pihole, the sync works, when there's a mismatch, the sync fails.

**Comment by Neobond** [comment]
I was getting the error 400 too and this helped me, it's now syncing:

```
nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    network_mode: host
    environment:
      - PRIMARY=http://127.0.0.1:8088|Password
      - REPLICAS=http://192.168.178.4:8088|Password
      - FULL_SYNC=false
      - SYNC_CONFIG_DNS=false
      - SYNC_CONFIG_DHCP=true
      - SYNC_CONFIG_NTP=true
      - SYNC_CONFIG_RESOLVER=true
      - SYNC_CONFIG_DATABASE=true
      - SYNC_CONFIG_MISC=true
      - SYNC_CONFIG_DEBUG=false
      - SYNC_GRAVITY_DHCP_LEASES=true
      - SYNC_GRAVITY_GROUP=true
      - SYNC_GRAVITY_AD_LIST=true
      - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
      - SYNC_GRAVITY_DOMAIN_LIST=true
      - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
      - SYNC_GRAVITY_CLIENT=true
      - SYNC_GRAVITY_CLIENT_BY_GROUP=true
      - CLIENT_TIMEOUT_SECONDS=60
      - RUN_GRAVITY=false
      - TZ=Europe/Amsterdam
      - CRON=*/5 * * * *
    restart: unless-stopped
```
