### ISSUE TITLE
Is my compose file messed up?

### ISSUE THREAD

**Issue by blimeybloke** [lovelaze/nebula-sync#18]
---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://192.168.0.12|password
    - REPLICAS=http://192.168.0.49|password
    - FULL_SYNC=true
    - CRON=0 * * * *

The docker starts but then in the log just sits there with:
2025-02-19T13:48:03Z INF Starting nebula-sync v0.2.5

I have a feeling it may be the urls?

**Comment by stanthewizzard** [comment]
in my case with 2FA I created a password app

**Comment by blimeybloke** [comment]
Its local which is why I am so hesitate to do 2fa.  I guess I could try it though.

**Comment by blimeybloke** [comment]
Nope, I created a new app pw for both instances, used it and it still failed.
Any chance you could share your docker file? Edited of course.

Thanks

**Comment by stanthewizzard** [comment]
```
---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    networks:
      - default
      - pihole
    environment:
    - PRIMARY=http://pihole|xxxxxxxxxxxxxxx
    - REPLICAS=http://192.168.0.32:6010|xxxxxxxxxxxxxxx
    - FULL_SYNC=true
    - CRON=0 */3 * * *
#    - CRON=* * * * *
    - TZ=Europe/xxxxxxxxxxxx

networks:
  default:
  pihole:
    name: pihole_default
    external: true
```

nebula and pihole master are on the same photon so I added pihole network to nebula
Removed 2FA (too messy for the moment)

Sync without issue
