### ISSUE TITLE
Docker secrets for passwords

### ISSUE THREAD

**Issue by gomeology** [lovelaze/nebula-sync#35]
I'm not a fan of putting passwords in docker compose. Can the envs be accompanied with __FILE so I can put the same info in a docker secret.

**Comment by lovelaze** [comment]
Yes, as @PhilThurston says this is already supported, although perhaps not in the way you request

**Comment by gomeology** [comment]
this is not implemented. At least not the proper way.

![Image](https://github.com/user-attachments/assets/22c8d767-92dc-4062-942c-99af74e34d97)

![Image](https://github.com/user-attachments/assets/8d97f738-48c4-4982-9141-b33c7637430c)

**Comment by lovelaze** [comment]
That's right, not using secret files.

Let's plan this as an enhancement!

**Comment by lovelaze** [comment]
#103 is ready to merge to support this

Caveat and why it's a draft:
It sets the `PRIMARY` and `REPLICAS` envs from the content of the secret files, in the nebula-sync process (and any other potentially spawned child processes..)

This is not really optimal but reading the file contents directly into the config structs while still supporting without `_FILE` requires a bit of refactoring, I haven't had time to do that yet.

Not sure if you want to try this out already or wait. The envs are of course not exposed in /etc/environment in the container, only for the running process

**Comment by lovelaze** [comment]
Implemented and released in [v0.9.0](https://github.com/lovelaze/nebula-sync/releases/tag/v0.9.0)

**Comment by dreary-ennui** [comment]
@lovelaze Thanks very much!

**Comment by dtseiler** [comment]
I'm a bit of a docker newbie, is there an example of how you'd use this? I see the run file reference in the PR but what would write the password to the file in the first place?

**Comment by dreary-ennui** [comment]
> I'm a bit of a docker newbie, is there an example of how you'd use this? I see the run file reference in the PR but what would write the password to the file in the first place?

@dtseiler 

Contents of docker-compose.yml:
```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    secrets:
      - primary
      - replicas
    environment:
    - NS_DEBUG=false
    - TZ=America/New_York
    - CLIENT_RETRY_DELAY_SECONDS=15
    - CLIENT_TIMEOUT_SECONDS=45
    - PRIMARY_FILE=/run/secrets/primary
    - REPLICAS_FILE=/run/secrets/replicas
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=*/15 * * * *


secrets:
  primary:
    file: ./secrets/primary.txt
  replicas:
    file: ./secrets/replicas.txt
```

I then create files ./secrets/primary.txt and ./secrets/replicas.txt with vim or whatever text editor I want.

Contents of primary.txt (just the string that would normally be in PRIMARY):
```
https://myprimarypihole.domain|thepassword
```

Contents of replicas.txt (just the string that would normally be in REPLICAS):
```
https://myfirstreplica.domain|itspassword,https://mysecondreplica.domain|anditspassword
```
