### ISSUE TITLE
Feature Request: Support Docker Swarm Secrets

### ISSUE THREAD

**Issue by Drallas** [lovelaze/nebula-sync#50]
Could you please add support for Docker Swarm secrets using the _FILE pattern? This approach is common in other Docker images (e.g., MySQL, WordPress) and enhances security by keeping secrets outside environment variables.

Suggested implementation:
- If PASSWORD is set, use it directly.
- If PRIMARY_PASSWORD_FILE exists, read the password from the file.

Example docker-compose.yml:

```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    environment:
      - PRIMARY=http://<ip>
      - PRIMARY_PASSWORD_FILE=/run/secrets/pi_app_password
      - REPLICAS=http://<ip>
      - REPLICA_PASSWORD_FILE=/run/secrets/pi_app_password
    secrets:
      - pi_app_password

secrets:
  pi_app_password:
    external: true
```

This would allow the app to securely fetch secrets without exposing them via docker inspect.

Thanks for considering this improvement!
