### ISSUE TITLE
Don't sync custom DNS

### ISSUE THREAD

**Issue by Tama47** [lovelaze/nebula-sync#61]
How to prevent this part from syncing?
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/d8bfb068-653e-43d7-8461-144e52327dc3" />
```
nebula-sync:
  image: ghcr.io/lovelaze/nebula-sync:latest
  container_name: nebula-sync
  environment:
    - PRIMARY=http://192.168.1.10:8080|
    - REPLICAS=http://192.168.1.15|
    - SYNC_CONFIG_DNS=false
    - FULL_SYNC=true
    - CRON=0 * * * *
  networks: {}
  restart: unless-stopped
```

When `FULL_SYNC=false`, nothing is syncing. Do I need to manually set each to true?
