### ISSUE TITLE
Ability to retry with delay

### ISSUE THREAD

**Issue by h0m3** [lovelaze/nebula-sync#65]
I have a setup with some Pi-Holes on Docker Swarm, and unfortunately the docker stack syntax doensn't allow me to wait for the Pi Hole instances to startup before spawning the nebula-sync instance, which makes the nebula-sync instance crash and start another container:

```
2025-03-08T00:26:27-03:00 INF Starting nebula-sync v0.6.0
2025-03-08T00:26:27-03:00 INF Running sync mode=full replicas=2
2025-03-08T00:26:27-03:00 INF Authenticating clients...
2025-03-08T00:26:27-03:00 FTL Sync failed error="authenticate: http://pihole_pihole1/api/auth: Post \"http://pihole_pihole1/api/auth\": dial tcp: lookup pihole_pihole1 on 127.0.0.11:53: no such host"
```

Since Pi-Hole takes a while to start if left default I endup with about 10 crashed containers and one online. The workaround I've found is to add a restart-policy with a 60 seconds delay:

``` yaml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
```

But that still create a container, then it crashes and then the second one is able to connect to Pi-Hole. I would like to ask if its possible to add a retry functionality with a delay on the service instead of the service exiting if its unable to talk with Pi-Hole.

**Comment by h0m3** [comment]
> Due to your log entry being fatal I'm wondering if http://pihole_pihole1/ is your primary. If so there are no retries for the primary. I'm not a maintainer, but from what I assume the premise of this app is that the primary needs to be available hence no retries, but changes to the replicas can take time. This is all due to the fact that like you said restarts can take some time and the primary is never modified in a way that requires a restart or anything else that would affect it's uptime.
> 
> Maybe adding retries for primary to the authentication call would solve your use-case, but it is a very rare use-case and the way I would do it is having swarm setup so that your pihole primary is it's own service to act as a source of truth and then the replicas have their number of replicas.

Thanks for the fast reply, you're totally right,

This only happens when the stack starts, which the primary is not available yet. My swarm stack is like that, the primary is its own service.

I dont think this situation would happen unless both primary and sync goes unavailable due to outages, updates or setup really, its a very rare use case indeed.

For reference, thats my stack, with sensitive information removed:

```yaml
services:

  pihole1:
    image: pihole/pihole:latest
    ports:
      - target: 80
        published: 10080
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    networks:
      - pihole
    environment:
      FTLCONF_LOCAL_IPV4: 10.10.10.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node_a]

  pihole2:
    image: pihole/pihole:latest
    ports:
      - target: 80
        published: 10080
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    networks:
      - pihole
    environment:
      FTLCONF_LOCAL_IPV4: 10.10.10.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node_b]

  pihole3:
    image: pihole/pihole:latest
    ports:
      - target: 80
        published: 10080
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    networks:
      - pihole
    environment:
      FTLCONF_LOCAL_IPV4: 10.10.10.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == node_c]

  sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    environment:
      PRIMARY: "http://pihole_pihole1|pw"
      REPLICAS: "http://pihole_pihole2|pw,http://pihole_pihole3|pw"
      FULL_SYNC: "true"
      RUN_GRAVITY: "false"
      CRON: "0 * * * *"
    networks:
      - pihole
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s


networks:
  pihole:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
          - subnet: 10.10.10.10/24
```
