### ISSUE TITLE
replica stops working after nebula sync run

### ISSUE THREAD

**Issue by balpert89** [lovelaze/nebula-sync#69]
Hi,

I am trying to sync my 2 pihole instances running with the official pihole docker setup.

pihole-01 docker-compose.yaml

```
---
version: '3'

services:
  nebula-sync:
    container_name: pihole-nebula-sync
    image: ghcr.io/lovelaze/nebula-sync:v0.6.0
    network_mode: host
    environment:
      - PRIMARY=${PRIMARY_INSTANCE}|${API_PASSWORD}
      - REPLICAS=${SECONDARY_INSTANCE}|${API_PASSWORD}
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - FULL_SYNC=false
      - RUN_GRAVITY=true
      - CRON=0 * * * *
      - TZ=${TZ}
      - SYNC_CONFIG_DHCP=true
      - SYNC_CONFIG_DHCP_LEASES=true
      - SYNC_CONFIG_NTP=true
      - SYNC_CONFIG_RESOLVER=true
      - SYNC_CONFIG_DATABASE=true
      - SYNC_CONFIG_MISC=true
      - SYNC_CONFIG_DEBUG=true
      - SYNC_CONFIG_GROUP=true
      - SYNC_CONFIG_AD_LIST=true
      - SYNC_CONFIG_AD_LIST_BY_GROUP=true
      - SYNC_CONFIG_DOMAIN_LIST=true
      - SYNC_CONFIG_DOMAIN_LIST_BY_GROUP=true
      - SYNC_CONFIG_CLIENT=true
      - SYNC_CONFIG_CLIENT_BY_GROUP=true
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    restart: unless-stopped
    volumes:
      - pihole:/etc/pihole
      - pihole.dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${API_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '127.0.0.1#5354;${SECONDARY_INSTANCE}#5354'
```

pihole-02 docker-compose.yaml

```
---
version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    restart: unless-stopped
    volumes:
      - pihole:/etc/pihole
      - pihole.dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${API_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: '127.0.0.1#5354;${SECONDARY_INSTANCE}#5354'

volumes:
  pihole:
  pihole.dnsmasq:
```

I am experiencing a problem where the nebula-sync run occurs and is successful, the pihole-02 gets unresponsive which is only solved with a `docker compose restart`.

logs pihole-01 nebula-sync:
```
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Starting nebula-sync v0.6.0
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Running sync mode=selective replicas=1
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Authenticating clients...
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Syncing Teleporters...
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Syncing configs...
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Running gravity...
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Invalidating sessions...
pihole-nebula-sync  | 2025-03-10T10:08:39+01:00 INF Sync complete
```

logs pihole-02 pihole:
```
pihole  | 2025-03-10 10:06:20.521 CET [51M] INFO: Web server ports:
pihole  | 2025-03-10 10:06:20.521 CET [51M] INFO:   - 0.0.0.0:80 (HTTP, IPv4, optional, OK)
pihole  | 2025-03-10 10:06:20.521 CET [51M] INFO:   - 0.0.0.0:443 (HTTPS, IPv4, optional, OK)
pihole  | 2025-03-10 10:06:20.521 CET [51M] INFO:   - [::]:80 (HTTP, IPv6, optional, OK)
pihole  | 2025-03-10 10:06:20.521 CET [51M] INFO:   - [::]:443 (HTTPS, IPv6, optional, OK)
pihole  | 2025-03-10 10:06:20.522 CET [51M] INFO: Restored 1 API session from the database
pihole  | 2025-03-10 10:06:20.531 CET [51M] INFO: Blocking status is enabled
pihole  | 2025-03-10 10:06:20.622 CET [51/T61] INFO: Compiled 0 allow and 0 deny regex for 3 clients in 0.3 msec

# here the sync happens
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring file etc/pihole/pihole.toml in Teleporter archive (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring file etc/pihole/dhcp.leases in Teleporter archive (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table group in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table adlist in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table adlist_by_group in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table domainlist in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table domainlist_by_group in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table client in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.843 CET [51/T127] INFO: Ignoring table client_by_group in etc/pihole/gravity.db (not in import list)
pihole  | 2025-03-10 10:08:39.845 CET [51/T127] INFO: Restarting FTL: Teleporter (ZIP) import
pihole  | 2025-03-10 10:08:39.845 CET [51M] INFO: Asked to terminate by "/usr/bin/pihole-FTL no-daemon" (PID 51, user pihole UID 1000)
pihole  | 2025-03-10 10:08:39.868 CET [51/T129] INFO: No config changes detected
pihole  | 2025-03-10 10:08:39.873 CET [51/T64] INFO: Terminating timer thread
pihole  | 2025-03-10 10:08:39.916 CET [51/T61] INFO: Terminating database thread
pihole  | 2025-03-10 10:08:40.096 CET [51M] INFO: Finished final database update
pihole  | 2025-03-10 10:08:40.096 CET [51M] INFO: Waiting for threads to join
pihole  | 2025-03-10 10:08:40.097 CET [51M] INFO: Thread housekeeper (1) is idle, terminating it.
pihole  | 2025-03-10 10:08:40.097 CET [51M] INFO: Thread dns-client (2) is idle, terminating it.
pihole  | 2025-03-10 10:08:40.097 CET [51M] INFO: All threads joined
pihole  | 2025-03-10 10:08:40.097 CET [51M] INFO: PID file emptied
pihole  | 2025-03-10 10:08:40.098 CET [51M] INFO: Stored 1 API session in the database
```

curl on pihole-02 after sync and after restart:
```
root@pi-dns-02:~/pi-dns-02/pihole# curl https://localhost -vk
* Host localhost:443 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:443...
* connect to ::1 port 443 from ::1 port 60550 failed: Connection refused
*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 from 127.0.0.1 port 40932 failed: Connection refused
* Failed to connect to localhost port 443 after 0 ms: Could not connect to server
* closing connection #0
curl: (7) Failed to connect to localhost port 443 after 0 ms: Could not connect to server

root@pi-dns-02:~/pi-dns-02/pihole# docker compose restart
[+] Restarting 1/1
 ✔ Container pihole  Started                                                                                                                                                                                                                          10.4s

root@pi-dns-02:~/pi-dns-02/pihole# curl https://localhost -vk
* Host localhost:443 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:443...
* Connected to localhost (::1) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server did not agree on a protocol. Uses default.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 403 Forbidden
```

any suggestions where I should start looking?
