### ISSUE TITLE
FTL Sync failed error="authenticate: http:

### ISSUE THREAD

**Issue by iamtapu** [lovelaze/nebula-sync#70]
Hopefully can get some help. What am I doing wrong? 

PRIMARY and REPLICAS pihole version: 

> Core version is v6.0.5 (Latest: v6.0.5)
> Web version is v6.0.2 (Latest: v6.0.2)
> FTL version is v6.0.4 (Latest: v6.0.4)

My docker compose file: 

```
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
      - PRIMARY=http://192.168.1.59|dog999
      - REPLICAS=http://192.168.1.81|dog999
      - FULL_SYNC=true
      - CRON=0 * * * *
      - INSECURE_SSL=true
    restart: unless-stopped
```

Getting error: 

```
nebula-sync> docker compose logs -f
nebula-sync  | 2025-03-12T01:03:14Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:03:14Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-12T01:03:14Z INF Authenticating clients...
nebula-sync  | 2025-03-12T01:03:14Z FTL Sync failed error="authenticate: http://192.168.1.59/api/auth: Post \"http://192.168.1.59/api/auth\": dial tcp 192.168.1.59:80: connect: connection refused"
nebula-sync  | 2025-03-12T01:03:14Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:03:14Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-12T01:03:14Z INF Authenticating clients...
nebula-sync  | 2025-03-12T01:03:14Z FTL Sync failed error="authenticate: http://192.168.1.59/api/auth: Post \"http://192.168.1.59/api/auth\": dial tcp 192.168.1.59:80: connect: connection refused"
nebula-sync  | 2025-03-12T01:03:15Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:03:15Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-12T01:03:15Z INF Authenticating clients...
nebula-sync  | 2025-03-12T01:03:15Z FTL Sync failed error="authenticate: http://192.168.1.59/api/auth: Post \"http://192.168.1.59/api/auth\": dial tcp 192.168.1.59:80: connect: connection refused"
nebula-sync  | 2025-03-12T01:03:15Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:03:15Z INF Running sync mode=full replicas=1
```

I have tried changing to httpS instead of http.

but still get error:
```
docker compose logs -f
nebula-sync  | 2025-03-12T01:08:43Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:08:43Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-12T01:08:43Z INF Authenticating clients...
nebula-sync  | 2025-03-12T01:08:43Z FTL Sync failed error="authenticate: https://192.168.1.59/api/auth: Post \"https://192.168.1.59/api/auth\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.1.59 because it doesn't contain any IP SANs"
nebula-sync  | 2025-03-12T01:08:43Z INF Starting nebula-sync v0.6.0
nebula-sync  | 2025-03-12T01:08:43Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-12T01:08:43Z INF Authenticating clients...
nebula-sync  | 2025-03-12T01:08:43Z FTL Sync failed error="authenticate: https://192.168.1.59/api/auth: Post \"https://192.168.1.59/api/auth\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.1.59 because it doesn't contain any IP SANs"
```

**Comment by tazzytazzy** [comment]
Getting the same issue. 

pihole-nebula-sync  | 2025-03-11T19:58:55-07:00 FTL Sync failed error="authenticate: http://10.133.144.2/api/auth: Post \"http://10.133.144.2/api/auth\": dial tcp 10.133.144.2:80: connect: connection refused"
pihole-nebula-sync exited with code 1

Versions:


Docker Tag [2025.03.0
Core [v6.0.5]
FTL [v6.0.4]
Web interface [v6.0.2]

**Comment by tazzytazzy** [comment]
Try changing to port 7003, worked for me afterwards. 

```
    environment:
      - PRIMARY=http://192.168.1.59:7003|dog999
      - REPLICAS=http://192.168.1.81:7003|dog999
```

Also, add a healthcheck in your pihole service:
```
    healthcheck:
        test: ["CMD", "curl", "-f", "http://10.133.144.2:7003/admin/"]
        interval: 30s
        timeout: 5s
        retries: 5
```

Then in your nebula-sync service, add a depends_on:
```
    depends_on:
      pihole:
        condition: service_healthy
```

Now, the nebula service won't start until pihole is fully operational.
