### ISSUE TITLE
Error during sync error="sync teleporters: https://10.0.0.1:9443/api/teleporter: unexpected status code: 500"

### ISSUE THREAD

**Issue by colfin22** [lovelaze/nebula-sync#80]
Seems to authenticate but then fails

````
root@docker-various:/opt/nebula# docker compose up
[+] Running 1/1
 ✔ Container nebula-sync  Created                                                                                         0.0s 
Attaching to nebula-sync
nebula-sync  | 2025-03-22T14:32:13Z INF Starting nebula-sync v0.7.0
nebula-sync  | 2025-03-22T14:32:13Z INF Running sync mode=full replicas=1
nebula-sync  | 2025-03-22T14:32:13Z INF Authenticating clients...
nebula-sync  | 2025-03-22T14:32:14Z INF Syncing teleporters...
nebula-sync  | 2025-03-22T14:32:14Z ERR Error during sync error="sync teleporters: https://10.0.0.1:9443/api/teleporter: unexpected status code: 500"
nebula-sync  | 2025-03-22T14:32:14Z INF Invalidating sessions...
nebula-sync  | 2025-03-22T14:32:14Z FTL Sync failed
nebula-sync exited with code 1
````

````
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=https://10.0.0.1:9443|XXXXWxqht+neBpZP6fi0no1TMxKX11FKcocvVOjKc0k=
    - REPLICAS=https://10.0.0.250|XXXXFu1rdm93JXLTo+NMAfVJwpbYelwpjvzsoA5Cvnw=
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    - CLIENT_SKIP_TLS_VERIFICATION=true
````
