### ISSUE TITLE
[FR] Healthcheck for the container

### ISSUE THREAD

**Issue by quorn23** [lovelaze/nebula-sync#94]
Would be awesome if you could add a health check (is the binary running for example)
Something like this [https://dozzle.dev/guide/agent#setting-up-healthcheck](https://dozzle.dev/guide/agent#setting-up-healthcheck) would be great, i monitor my container and this would enable to monitor the container, in case nebula crashes or hangs etc. 

There's stuff like [https://github.com/canidam/docker-go-healthcheck](https://github.com/canidam/docker-go-healthcheck), but i'm not a Go coder, so there might be nicer approaches.

Example:
```
    healthcheck:
      test: ["CMD", "/nebula-sync", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
```
